### ISSUE TITLE
项目Sql语句

### ISSUE THREAD

**Issue by ghost** [MineCoinChain/WEHousing#1]
您好，请问这个项目的SQL语句在哪哈，方便加下联系方式嘛

**Comment by MineCoinChain** [comment]
> 您好，请问这个项目的SQL语句在哪哈，方便加下联系方式嘛

在IHomeWeb目录的conf下，忘了分出来了，不过我已经添加了一个sql文件夹里边也有。

**Comment by ghost** [comment]
好的，感谢 ------------------ 原始邮件 ------------------
发件人: "ZhangGuo"<notifications@github.com>
发送时间: 2019年7月21日(星期天) 下午4:49
收件人: "MineCoinChain/WEHousing"<WEHousing@noreply.github.com>;
抄送: "ffgfg"<1652208024@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MineCoinChain/WEHousing] 项目Sql语句 (#1)


 
您好，请问这个项目的SQL语句在哪&#x54C8;，方便加下联系方式嘛
  
在IHomeWeb目录的conf下，忘了分出来了，不过我已经添加了一个sql文&#x4EF6;夹里边也有。
 
&mdash;
