### ISSUE TITLE
Sql建表语句

### ISSUE THREAD

**Issue by lcl1024** [MineCoinChain/WEHousing#2]
你好，请问项目的Sql建表语句可不可以发一下呢

**Comment by MineCoinChain** [comment]
在sql文件夹下有一个data.sql

**Comment by lcl1024** [comment]
那个是导入数据的sql，我想要一下建表的语句有没有呢

**Comment by MineCoinChain** [comment]
beego的ORM

**Comment by MineCoinChain** [comment]
玩过beego滴不？ORM可以直接建表，只需要写model

**Comment by MineCoinChain** [comment]
IhomeWeb下model里的models.go

**Comment by lcl1024** [comment]
谢谢，我研究下

**Comment by MineCoinChain** [comment]
可以看一下beego的官方文档，https://beego.me/docs/quickstart/model.md，原来你们都在问建表语句，我以为是数据文件。
