### ISSUE TITLE
GetUserOrder模块出现问题

### ISSUE THREAD

**Issue by lcl1024** [MineCoinChain/WEHousing#4]
您好，我在运行GetUserOrder模块的时候出现了
`
subscriber/example.go:12:52: undefined: go_micro_srv_GetUserOrder.Message
subscriber/example.go:17:40: undefined: go_micro_srv_GetUserOrder.Message
`
这样的错误信息

**Comment by MineCoinChain** [comment]
将subscriber里边的example.go删除掉就可以了，或者把example.go里边的错误代码删掉，这个模块没有使用proto如果运行后可能会出问题。

**Comment by lcl1024** [comment]
mian.go中有这么一段代码
`
micro.RegisterSubscriber("go.micro.srv.GetUserOrder", service.Server(), new(subscriber.Example))

micro.RegisterSubscriber("go.micro.srv.GetUserOrder", service.Server(), subscriber.Handler)
`
这里调用了订阅服务，这里是可以删掉的是吗？

**Comment by MineCoinChain** [comment]
是的
