### ISSUE TITLE
GetArea模块中数据获取逻辑问题

### ISSUE THREAD

**Issue by lcl1024** [MineCoinChain/WEHousing#5]
你好，在GetArea模块中当进行数据获取的时候有这么一个逻辑，先去redis中获取数据，如果有数据则将缓存中的数据发送给web，没有数据则去mysql中获取，我想这里应该是为了在查找房产信息的时候使用之前选定的区域而做的逻辑。
但是会导致在首页出现一个问题，当你选择了区域信息后，点击搜索，再回到首页来会发现现在只有你之前选择的area了，无法将数据库中的信息读出来，如图
![Snipaste_2019-08-21_15-01-53](https://user-images.githubusercontent.com/35106934/63409987-d4d36000-c424-11e9-8bb9-b2ae630a45e7.png)
同理，进入到房源列表的时候也会出现这样的bug。
![Snipaste_2019-08-21_15-01-53](https://user-images.githubusercontent.com/35106934/63410193-4d3a2100-c425-11e9-88d7-6ef4dcb3a332.png)
这次issue语言组织的有些啰嗦，希望您能见谅。

**Comment by lcl1024** [comment]
我觉得应该是有一个FLUSHALL redis的地方，但是我没有找到，希望您能告诉我一下在哪里触发的

**Comment by MineCoinChain** [comment]
这个地方的redis和mysql之间的逻辑很简单，就是通过缓存降低数据库压力，正常情况下访问redis降低mysql的查询压力，没有说标定之前选中的什么的，也不需要flush，因为针对这个地域模块我们目前不用，也不做处理，只是展示一下。OK有时间的话，帮忙查改一下bug吧，貌似还挺多的，我最近在找工作有点儿忙。Thanks。
